### ISSUE TITLE
[Feature] 동네 입력 모달 만들기 

### ISSUE THREAD

**Issue by youngkyo0504** [woowa-techcamp-2022/web-fleamarket-03#15]
## 이슈 설명

- 동네를 입력할 수 있는 모달을 만든다. (페이지 형태)
- 모달은 페이지 형태이다. 

## 필요한 작업 내용

- [x] 모달이 오른쪽에서 왼쪽으로 등장한다. 
- [x] 입력창에서 동네를 검색할 수 있다. 
- [x] 동네를 검색할 때는 debounce, throttle과 같은 최적화 작업이 필요하다. 
- [ ] (optional) infinite 스크롤링을 구현한다. 
- [x] 동네를 선택하면 모달이 닫힌다.
- [x] 뒤로가기 버튼을 누르면 모달이 닫힌다. 

## 예상 시간

**Comment by happyGyu** [comment]
무한 스크롤링은 백엔드, 프론트 로직이 많이 추가되어야하고 훅으로 만들수 있을 것 같아서 추후 별도의 이슈로 수행
